[package]
name = "mncalc"
version = "0.1.0"
authors = ["Ignacio Arces <arcesino@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.14"
spectral = "0.6.0"
regex = "1"
lazy_static = "1.2.0"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
